export const ACTION = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  CONFIRM_EDIT_TODO: 'CONFIRM_EDIT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  FILTER_TODO: 'FILTER_TODO',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
};
