export const ACTION = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  CONFIRM_EDIT_TODO: 'CONFIRM_EDIT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  FILTER_ALL_TODO: 'FILTER_ALL_TODO',
  FILTER_ACTIVE_TODO: 'FILTER_ACTIVE_TODO',
  FILTER_COMPLETED_TODO: 'FILTER_COMPLETED_TODO',
};
